export const POKEMON_TYPES = {
  normal: "NORMAL",
  fire: "FIRE",
  water: "WATER",
  electric: "ELECTRIC",
  grass: "GRASS",
  ice: "ICE",
  fighting: "FIGHTING",
  poison: "POISON",
  ground: "GROUND",
  flying: "FLYING",
  psychic: "PSYCHIC",
  bug: "BUG",
  rock: "ROCK",
  ghost: "GHOST",
  dragon: "DRAGON",
  dark: "DARK",
  steel: "STEEL",
  fairy: "FAIRY",
} as const;

export const TYPE_CHART: Record<string, Record<string, number>> = {
  // Normal-type interactions
  normal: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 0,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  // Fire-type interactions
  fire: {
    normal: 1,
    fire: 0.5,
    water: 2,
    electric: 1,
    grass: 0.5,
    ice: 0.5,
    fighting: 1,
    poison: 1,
    ground: 2,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 0.5,
    fairy: 0.5,
  },
  // Water-type interactions
  water: {
    normal: 1,
    fire: 0.5,
    water: 0.5,
    electric: 2,
    grass: 2,
    ice: 0.5,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 0.5,
    fairy: 1,
  },
  // Electric-type interactions
  electric: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 0.5,
    grass: 1,
    ice: 1,
    fighting: 1,
    poison: 1,
    ground: 2,
    flying: 0.5,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 0.5,
    fairy: 1,
  },
  // Grass-type interactions
  grass: {
    normal: 1,
    fire: 2,
    water: 0.5,
    electric: 0.5,
    grass: 0.5,
    ice: 2,
    fighting: 1,
    poison: 2,
    ground: 0.5,
    flying: 2,
    psychic: 1,
    bug: 2,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  // Ice-type interactions
  ice: {
    normal: 1,
    fire: 2,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 0.5,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 2,
    fairy: 1,
  },
  // Fighting-type interactions
  fighting: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 2,
    psychic: 2,
    bug: 0.5,
    rock: 0.5,
    ghost: 1,
    dragon: 1,
    dark: 0.5,
    steel: 1,
    fairy: 2,
  },
  // Poison-type interactions
  poison: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 0.5,
    ice: 1,
    fighting: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 1,
    psychic: 2,
    bug: 0.5,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 0.5,
  },
  // Ground-type interactions
  ground: {
    normal: 1,
    fire: 1,
    water: 2,
    electric: 0,
    grass: 2,
    ice: 2,
    fighting: 1,
    poison: 0.5,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 0.5,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  // Flying-type interactions
  flying: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 2,
    grass: 0.5,
    ice: 2,
    fighting: 0.5,
    poison: 1,
    ground: 0,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  // Psychic-type interactions
  psychic: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 0.5,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 0.5,
    bug: 2,
    rock: 1,
    ghost: 2,
    dragon: 1,
    dark: 2,
    steel: 1,
    fairy: 1,
  },
  // Bug-type interactions
  bug: {
    normal: 1,
    fire: 2,
    water: 1,
    electric: 1,
    grass: 0.5,
    ice: 1,
    fighting: 0.5,
    poison: 1,
    ground: 0.5,
    flying: 2,
    psychic: 1,
    bug: 1,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  // Rock-type interactions
  rock: {
    normal: 0.5,
    fire: 0.5,
    water: 2,
    electric: 1,
    grass: 2,
    ice: 1,
    fighting: 2,
    poison: 0.5,
    ground: 2,
    flying: 2,
    psychic: 0.5,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 2,
    fairy: 1,
  },
  // Ghost-type interactions
  ghost: {
    normal: 0,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 0,
    poison: 0.5,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 1,
    ghost: 2,
    dragon: 1,
    dark: 2,
    steel: 1,
    fairy: 1,
  },
  // Dragon-type interactions
  dragon: {
    normal: 1,
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    grass: 0.5,
    ice: 2,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 2,
    dark: 1,
    steel: 1,
    fairy: 2,
  },
  // Dark-type interactions
  dark: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 0,
    bug: 2,
    rock: 1,
    ghost: 0.5,
    dragon: 1,
    dark: 0.5,
    steel: 1,
    fairy: 2,
  },
  // Steel-type interactions
  steel: {
    normal: 0.5,
    fire: 2,
    water: 1,
    electric: 1,
    grass: 0.5,
    ice: 0.5,
    fighting: 2,
    poison: 0,
    ground: 2,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 0.5,
    ghost: 1,
    dragon: 0.5,
    dark: 1,
    steel: 0.5,
    fairy: 0.5,
  },
  // Fairy-type interactions
  fairy: {
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 0.5,
    poison: 2,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 1,
    ghost: 1,
    dragon: 0,
    dark: 0.5,
    steel: 2,
    fairy: 1,
  },
}